[project]
name        = 'rx_common'
description = 'Project used to find and load libraries in cal-rx-run3 c++ code'
version     = '0.0.2'
readme      = 'README.md'
dependencies= [
'data-manipulation-utilities',
'PyYAML',
'rx_data',
]

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']

[project.scripts]
make_run3_yaml='rx_common_scripts.make_run3_yaml:main'
lfn_to_yaml='rx_common_scripts.lfn_to_yaml:main'

[tool.setuptools.package-data]
'rx_config' = ['*.yaml']
'rx_tests'  = ['kernel/*.yaml']

[tool.setuptools]
script-files=[]
